### ISSUE TITLE
Readme file crashed

### ISSUE THREAD

**Issue by amrit110** [hoxovic/hemnet-crawler#1]
Hello hoxovix, i tried to run the readme file. crashed with an errors. i'm running windows vista. Help! I tried debugg, maybe this is the issue?
![readme](https://user-images.githubusercontent.com/8986523/66845091-71a20d80-ef3d-11e9-8125-cd2c564ef412.png)

**Comment by hoxovic** [comment]
Have you tried turning your computer off and on again?

**Comment by hoxovic** [comment]
I did that once and the troubleshooter uninstalled Windows. That solved all problems.

**Comment by amrit110** [comment]
Thanks, that was the issue. readme works perfectly! Im closing this.
